title: Cybersecurity Blog
author: BassamKhan
description: The Hacker Plus Theme
google_analytics:
google_site_verification_content: 
disqus_forum_shortname: https-masterchief220-github-io-blogging-website

#Usernames and badges
htb_badge_no: #issues with htb badge
thm_badge_no: 1442295
show_thm_htb_badges_in_nav: true
github_username: MasterChief220
gitlab:
medium: https://medium.com/@bassam-khan
stackoverflow:
hacker_news:
linkedin: mbassamkhan
twitch:
youtube:
twitter: 
facebook:
instagram:
reddit:
pinterest: bassamexe
telegram:
steam:

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true